### PR TITLE
Remove top imports

### PR DESCRIPTION
**Pull request by nden**
Here's one way to change imports. The top level `__init__.py` import everything from `datamodels`. 
This will allow users to run `from jwst import MyFavouriteModel`. All other imports are moved to a new module called (semi-randomly) `steps`. Now we can set up an "aliveness"  test which does

```
import jwst
from jwst import steps
```

How is this going to work with CRDS?
Should we move the `datamodels` import into `steps` as well?

@jaytmiller @hbushouse @jhunkeler @stsci-hack

### CODE REVIEW

**Comment by hbushouse** [comment]
Does the steps.py module only exist for the purpose of running it as an aliveness test? It doesn't get used anywhere else within any other init's or actual code modules?

**Comment by nden** [comment]
@hbushouse Yes, that's it. Also you can say

```
from steps import *
```
and get them all (in a custom pipeline, for example).

**Comment by jaytmiller** [comment]
That probably solves my CRDS concerns assuming that datamodels doesn't 
have the same basic "import everything" problem.

But for your second question,  IMHO we should keep __init__ empty where 
feasible.  So put datamodels in "steps" too.

Todd

**Comment by nden** [comment]
OK, moved `datamodels` to `steps` too.

**Comment by nden** [comment]
Should we go ahead with this?

**Comment by jaytmiller** [comment]
On Jun 10 2016 3:18 PM, Nadia Dencheva wrote:
>
> Should we go ahead with this?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub 
> <https://github.com/STScI-JWST/jwst/pull/40#issuecomment-225271892>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/AAjc2BDupse0ohzHYAoOg-8YgyF_9xV4ks5qKbh4gaJpZM4Iy7mn>.
>
+1 here.

**Comment by hbushouse** [comment]
👍

**Pull request merged**
