### PR TITLE
Convert reference data from float to complex.

### PR DESCRIPTION
**Pull request by philhodge**
The schema for the IRS2 reference file was changed to specify that the
columns are float32 rather than complex64.  irs2_subtract_reference.py
was modified to convert these values to complex.
See GitHub issue #1277 and JIRA ticket JP-181.

### CODE REVIEW

**Comment by hbushouse** [comment]
Should we wait to merge this until the new format ref files get installed in CRDS? Otherwise it won't be able to read the existing ref files that store things as complex.

**Comment by philhodge** [comment]
The new format reference files already are in CRDS; that was the problem.  The new ones have float data that contain alternating real and imaginary parts, while the original ones have complex data.  The code in this PR will work with the new reference files and will not work with the original reference files.  I couldn't make it work with either format of reference file without having two separate IRS2Models, and I didn't think it was worth the bother.  The NIRSpec team must have known that the original reference files had complex data, but they delivered their new ones with float data, so I'm assuming they will continue to deliver float data in the future.

**Comment by hbushouse** [comment]
CRDS context 409 contains an updated NIRSpec refpix rmap that now includes the new refpix ref files and removes the old ones. So as soon as testing of this code is satisfied it can be merged.

**Comment by philhodge** [comment]
The Linux tests have passed, but the Mac tests haven't even started yet (after three hours).  Merging.

**Pull request merged**
