### PR TITLE
msa shutter numbers in the MSA ref file are 1 based

### PR DESCRIPTION
**Pull request by nden**

### CODE REVIEW

**Comment by nden** [comment]
@drdavella Are the failures here fixed already in asdf?

**Comment by drdavella** [comment]
@nden, @hbushouse this isn't really a bug: in some sense there has been an API change in ASDF with respect to history entries. I have added a workaround in ASDF (see https://github.com/spacetelescope/asdf/pull/487). In the long term, it might be a good idea for datamodels to update the way that it writes history entries (I can take on that task if you want).

**Comment by hbushouse** [comment]
Travis still failing, despite the fact that  spacetelescope/asdf#487 has been merged. Is the Travis build pulling from the asdf master?

**Comment by nden** [comment]
Travis uses the nightly builds. I'll see if I can fix it in this PR.

**Comment by nden** [comment]
@drdavella Can you take a look at the last commit here - the one that's supposed oto fix the history format - see if it looks OK. Thanks.

**Comment by drdavella** [comment]
@nden it looks good but there is still a warning coming from `test_history_from_fits`. I'm not sure how important it is to track down right now, though.

**Comment by nden** [comment]
I am still missing something. There's code somewhere which transforms FITS type HISTORY keywords into a list of entries and saves it as `DataModel.history` .

**Comment by bernie-simon** [comment]
It's _load_history in fits_support.py

**Comment by nden** [comment]
Let's see if this fixes it.

**Comment by nden** [comment]
:tada: merging ...

**Pull request merged**
