### PR TITLE
adding script to add telescope pointing info to level-1b file

### PR DESCRIPTION
**Pull request by perrygreenfield**

### CODE REVIEW

**Comment by hbushouse** [comment]
@nden @perrygreenfield According to the doc string this currently computes RA_V1, DEC_V1, and PA_V3 (among others). I believe we also wanted to compute RA_REF, DEC_REF, and ROLL_REF, which are the coords at the V2_REF/V3_REF point and the roll angle around that point. Correct?

**Comment by perrygreenfield** [comment]
Aren't the coordinates of that point identical to CRVAL1, 2? The roll angle is encoded in the PC matrix and derivable from it, but it could be added separately. But is ROLL_REF the right name for it, since it really doesn't have anything to do with the reference point?

**Comment by jemorrison** [comment]
Ra_REF and DEC_REF are the coordinates corresponding to v2_ref, v3_ref. 
For MIRI we have a problem that we have two fields of view per image so 
the standard WCS did not work. Roll_ref is the roll angle between the 
ra,dec and v2,v3 system at these points. For MIRI the V2_ref and V3_ref 
is defined to always be the center of the channel 1 a IFU. These new 
keywords allow us to transform images in the V2-V3 system because this 
is a common system for all 12 MIRI bands (channel, subchannel).  Though 
NIRSPEC does not have to conform to this method it is easier if both 
IFUs have a similar method of converting pixel values to ra,dec.
Jane

**Comment by nden** [comment]
Yes, `RA_REF` and `DEC_REF` are identical to `CRAVL1/2`.  `ROLL_REF` is actually computed at the reference point using `PA_V3` directly.
Not all teams have confirmed that they want to use this scheme. So far MIRI MRS and all NIRSpec modes will be using it.

**Comment by hbushouse** [comment]
@perrygreenfield @nden How are we handling multiaperture vs. individual detector reference points and coords in this? For example, in the case where the NRC_FULL aperture is used by an observation, are we assuming that SDP will already have known to retrieve entries from the SIAF corresponding to the individual detector apertures (as it processes the exposure resulting from each detector) and hence the values of V2_REF and V3_REF that are input to this script will already be the values for a particular detector? And hence CRVAL1/CRVAL2 will be sky coords at that detector-specific V2_REF/V3_REF location and will therefore be different for each exposure coming from a full-field observation? Meanwhile the RA_V1 and DEC_V1 values would be the same for all of the individual exposures (because the V1 axis is only pointed in one place for all of the exposures)?

**Comment by perrygreenfield** [comment]
Yes, for the moment I'm assuming they (SDP) provides the individual SIAF info for combined aperture. This is mainly because there is no point for them putting any siaf info in if we still have to access the SIAF info. Either we don't do any, or we do it all. A mix makes no sense.

**Comment by nden** [comment]
@perrygreenfield See my PR to this PR adding `ROLL_REF`, `RA_REF` and `DEC_REF`.

**Comment by nden** [comment]
Are `CTYEPE#`, `CUNIT#` and `RADESYS` populated anywhere or should this script populate them?

**Comment by hbushouse** [comment]
Right now CTYPE#, CUNIT#, etc. are populated in SDP when they create level-1b files. Not sure if they distinguish between imaging and spectroscopy modes such that they only include keywords for 2 axes for imaging and 3 for spectroscopy (they may just always include 3). It might make sense to move the population of these keywords to this routine just to keep it all together in one place. And speaking of differences between imaging and spectroscopy, I notice that this script only populates P1_# and P2_# keywords. Do we need to have P3_# entries for spectroscopic modes, even if they're just set to 0 and 1?

**Comment by philhodge** [comment]
If the data array is 3-D, I think the FITS WCS should be populated with 
something (even if dummy values) for all axes.  I got a warning from 
fitsverify in this regard:

=================== HDU 1: Primary Array ===================

*** Warning: Some CRPIXi keywords appear to be missing; expected 3.

**Comment by hbushouse** [comment]
@nden I just merged this to get it into master, so that continued work can be done on it. Can you commit/merge your PR that adds computation of RA_REF, DEC_REF, and ROLL_REF too? I/we need to talk with the SDP folks about what to do with the other keywords like CYTPEn and CUNITn. We might want to add those in here too.

**Pull request merged**
