### PR TITLE
Add model names to the output product listing

### PR DESCRIPTION
**Pull request by stscieisenhamer**
WIP #623

### CODE REVIEW

**Comment by stscieisenhamer** [comment]
@hbushouse Very minor thing, but started adding what the datamodels used are to the pipelines document. DIdn't find anyplace where this equivalency was done and thought this would be the place for it.

**Comment by stscieisenhamer** [comment]
Error is a build timeout. Will merge when discussion is complete.

**Comment by hbushouse** [comment]
This is a good idea. Very useful info for folks who want to work with the data using our models. In addition to adding the class names of the models in the text, there should also be some sort of brief introductory remark at the beginning indicating what those names are that appear in parentheses for each product.

**Comment by hbushouse** [comment]
One thing that will make this listing a bit messy is that there isn't always a one-to-one correspondence between a product type and data model. For example, _cal products can be in the form of an ImageModel for both imaging and simple spectra (like MIRI LRS), while other spectral _cal's use a MultiSlitModel.

**Comment by stscieisenhamer** [comment]
I presumed that was the case; exactly why such documentation would be good.

**Comment by stscieisenhamer** [comment]
All errors have to do with a CRDS issue unrelated to any changes. Merging.

**Pull request merged**
