### PR TITLE
autopep8 complaints (whitespace only)

### PR DESCRIPTION
**Pull request by jhunkeler**
# [DO NOT MERGE]

Use this to identify problem areas and fix them or vote to merge this as soon as possible. Merging will ruin "git blame" because it touches a huge chunk of the codebase, but since we already lost history that's not a big deal _for the moment_. 

# A visual aid

The majority of pep8's complaints regard invalid whitespace. Trailing whitespace, missing spaces, and spaces between keywords are the major culprits:

**Correction table:**

`print ( 'text' )` -> `print('text')`
`if variable : ` -> `if variable:`
`x = [ 1,2,3 ]` -> `x = [1, 2, 3]`

### CODE REVIEW

**Comment by nden** [comment]
:+1:  to merge as is as it will save us a lot of typing

**Comment by jdavies-st** [comment]
Agree with Nadia.  Looked at my code, and the changes look good.

**Comment by jhunkeler** [comment]
@nden @jdavies-st -- I added in the rest of the PEP8 requirements. This brings the total complaint down to 204. Apparently some of the code issues cannot be resolved automatically. In all cases it was due to having a `\` continuation on the line. 

204 is much better than 1,400 in any case.

**Comment by sosey** [comment]
yah - it'll give you a  \ error if the continuation was used inside a parenthetic statement (where it's not needed)

**Comment by jhunkeler** [comment]
@STScI-JWST/maintainers Does anyone else mind if we merge this? We have two votes for "yes".

**Comment by stscieisenhamer** [comment]
If non-compliant, is that test failure or just a warning?



Jonathan D. Eisenhamer
Science Software Branch,  STSCI
eisenhamer@stsci.edu
410-338-5073
g+: stscieisenhamer@gmail.com
aim/icq: triccare


-------- Original message --------

**Comment by nden** [comment]
@jhunkeler Is this PR easily reproducible by running a script? Should I merge first #58?

**Comment by hbushouse** [comment]
:+1: Merge it.

**Comment by jhunkeler** [comment]
@nden If #58 is ready for merge I can wait for it and re-execute the autopep8 on my branch.

**Comment by nden** [comment]
I'm trying to finalize it now by commenting out the failing tests and filing issues for them to be fixed.

**Comment by jhunkeler** [comment]
No rush -- just let me know 😃

**Pull request merged**
