### PR TITLE
Resample rc4

### PR DESCRIPTION
**Pull request by jdavies-st**

### CODE REVIEW

**Comment by jdavies-st** [comment]
@jhunkeler feel free to merge this and start your RC4 build once the TravisCI tests have completed.  Or at least once the Linux ones have.

**Comment by jhunkeler** [comment]
@jdavies-st Travis is having one of its outages again.
@hbushouse Want me to override and proceed?

**Comment by hbushouse** [comment]
Yes! Make rc4 if you haven't already.

Sent from my Verizon Wireless 4G LTE DROID


Joseph Hunkeler <notifications@github.com> wrote:


@jdavies-st<https://github.com/jdavies-st> Travis is having one of its outages again.
@hbushouse<https://github.com/hbushouse> Want me to override and proceed?

**Comment by jhunkeler** [comment]
🚀

**Comment by jhunkeler** [comment]
Done - email sent to the group

**Pull request merged**
