### PR TITLE
Model container asn open generalize

### PR DESCRIPTION
**Pull request by jdavies-st**
ModelContainer now opens any type of DataModel that can be handled by `datamodels.open()`.  datamodels.open() code has been relocated from `__init__.py` to `utils.py` to support this.  Finally, any keyword arguments that DataModel takes can now be passed through `datamodels.open()`.  This is useful for the `pass_invalid_values=True` keyword to disable strict schema checking.

### CODE REVIEW

**Comment by jdavies-st** [comment]
@hbushouse could you have a look to see if this solves your issues with ModelContainer?

**Comment by hbushouse** [comment]
Tried loading the ASN containing:

 {"prodtype": "coroncmb", "name": "jw89001-c1001_t001_nircam_f160w",
    "members": [
      {"exptype": "science", "expname": "test_targ1_calints.fits"}, 
      {"exptype": "science", "expname": "test_targ2_calints.fits"},
      {"exptype": "psf", "expname": "test_psf1_calints.fits"},
      {"exptype": "psf", "expname": "test_psf2_calints.fits"},
      {"exptype": "psf", "expname": "test_psf3_calints.fits"}]}],

where all of the members are CubeModels, and got:

In [1]: from jwst import datamodels
In [2]: cont=datamodels.open('test_coron_asn.json')
Opening test_targ1_calints.fits as <class 'jwst.datamodels.cube.CubeModel'>
Opening test_targ2_calints.fits as <class 'jwst.datamodels.cube.CubeModel'>
Opening test_psf1_calints.fits as <class 'jwst.datamodels.cube.CubeModel'>
Opening test_psf2_calints.fits as <class 'jwst.datamodels.cube.CubeModel'>
Opening test_psf3_calints.fits as <class 'jwst.datamodels.cube.CubeModel'>
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-3a1bac66350e> in <module>()
----> 1 cont=datamodels.open('test_coron_asn.json')

/Users/bushouse/anaconda/envs/myjwst/lib/python2.7/site-packages/jwst-0.6.0noop.dev460-py2.7-macosx-10.6-x86_64.egg/jwst/datamodels/util.pyc in open(init, extensions, **kwargs)
     59         except:
     60             raise TypeError(
---> 61                 "init ASN not valid for ModelContainer"
     62                 )
     63     elif isinstance(init, model_base.DataModel):

TypeError: init ASN not valid for ModelContainer

So it seemed to be recognizing and loading the 5 input files as CubeModel, which is correct, but then something went haywire after that?

**Comment by jdavies-st** [comment]
Thanks Howard.  I'd like your test data to see what's going on. I don't seem to be catching the error properly in the code.

**Comment by hbushouse** [comment]
The asn file and the FITS files are in /grp/jwst/ssb/bushouse/jwst_data/KLIP_data/. The name of the asn file is 'test_coron_asn.json'.

**Comment by jdavies-st** [comment]
It looks like the input ASN file has TARGNAME instead of TARGET, which caused the issue.  So malformed input json file.  Will add some error correction code to catch these in the future, but this can be merged now.

**Comment by hbushouse** [comment]
Yep, confirmed that when I changed "targname" to "target" in the ASN file it worked fine.

👍

**Pull request merged**
