### PR TITLE
Save arrays

### PR DESCRIPTION
**Pull request by nden**
I am proposing removing some of previous changes to `properties._cast`.
The problem I am trying to solve is to serialize numpy arrays directly to asdf files. Note that currently all numpy array serialization in datamodels is to FITS files which calls specialized code.
Serializing ndarrays works with asdf but not with datamodels.

Looking at the code in `properties._cast` removed in this PR, I think it was added to solve an issue with saving Time objects to FITS files using the core schema. I believe there was a bug/typo in the core schema which caused the Time object problems. So here I've also commented out and changed the `date` field in the core schema to use `anyOf` instead of `allOf`.

This is all motivate by work on #888 which is currently stalled until the problem with numpy arrays is solved.

### CODE REVIEW

**Comment by nden** [comment]
Failure is numpy 1.12 related.

**Comment by bernie-simon** [comment]
The reason for tagging in general is that yaml (and asdf) is a serialization of a data structure and the code needs to know the type of objects embedded in the structure so that it can recreate them when reading back from disk. The tagging is also used to validate an object against the schema. The tag attribute acts as a check of the object type.

**Comment by bernie-simon** [comment]
The tagging verifies that when you set a datamodels attribute to a complex object, like a date, that the type of the complex object agrees with the type that the schema expects. If there's no tag field in the schema, the check won't be performed, but if there is, the code needs to run through the tagging mechanism in asdf.

**Comment by nden** [comment]
@bernie-simon Agreed. However, complex objects already have tags in their schemas. For example

```
date:
  $ref: http://stsci.edu/schemas/asdf/time/time-1.0.0
```

contains the tag for Time objects.
I think only primitive python types, like lists, etc..., which normally don't have tags, need to be tagged. The custom types, like `Time` and `ndarray` are already tagged by definition. At least this is my understanding. In any case the code removed here breaks functionality. 
Can you provide an example which fails without this code?

**Comment by nden** [comment]
I am going to merge this and let the nightly tests run. It can always be reverted if needed.

**Pull request merged**
