### PR TITLE
Add version check

### PR DESCRIPTION
**Pull request by stsci-hack**
This PR adds a new module to report on the versions for all calibration pipeline steps, as well as a new script to enable a command-line interface for generating the version report as a JSON file.  The module has been added to the top level of the JWST package to allow it to inspect all sub-packages for any class that ends in 'Step'.  These versions of the file have already been found to be PEP8 compliant (by checking them with 'pep8' task).

### CODE REVIEW

**Comment by nden** [comment]
Hm, are we versioning now individual steps?
Didn't we just put all steps in one package?

**Comment by hbushouse** [comment]
We have a DMS level 4 requirement that says archive users have to be able to find out the version number of each calibration step that was used to create a calibrated product. Discussions intended to convince people of the relative lack of worth of such a thing have not succeeded in removing this requirement. Hence, in addition to the "global" version number of the jwst package, which is recorded in the CAL_VER keyword of pipeline output products, we must provide a mapping between CAL_VER and the version numbers of individual cal steps. The purpose of this tool is to gather the version numbers of each step/pipeline/subpackage in the tree and record them in a single file, which will be stored in CRDS and will be available to the archive CAOM system to show the individual version numbers when requested.

**Comment by hbushouse** [comment]
The pipeline sub-package is imported to this task via importing steps.py, which means we could include pipeline modules as well as individual steps. That would require scanning for class names that end in "Pipeline." Changing a pipeline module can certainly affect calibration results, so it's probably worthwhile to include the versions of those as well.

**Comment by stsci-hack** [comment]
The additional reporting of Pipeline versions can be added in the next revision to this code.  This raises a question about whether or not it can be included in the same list of version numbers as steps or whether it should have it's own list in the file, which can be done as well.  We just want to make sure the archive can cleanly interpret this file.  In the meantime, I will merge this in now, then add support for Pipeline versions next.

**Comment by hbushouse** [comment]
:+1:

**Pull request merged**
