### PR TITLE
Asn io

### PR DESCRIPTION
**Pull request by stscieisenhamer**
Encapsulate association serialization

### CODE REVIEW

**Comment by stscieisenhamer** [comment]
@jhunkeler just something to note: the travis builds appeared to have worked accept, at this point, build 73.8. At time of this comment, the last commit was done over 5 hours ago. Not sure what is happening.

**Comment by jhunkeler** [comment]
From https://www.traviscistatus.com/

> Increased boot times on Mac infrastructure
> Jun 22, 00:45 UTC
> Increased boot times on Mac infrastructure Subscribe
> Identified - We're working on cleaning up some stale VMs on our Mac infrastructure, you may experience increased boot times for the time being. 

We build on Linux and OSX so this might explain how/why things got so backlogged.

**Comment by stscieisenhamer** [comment]
"Increased boot times": Well, that's an understatement.
________________________________

**Comment by stscieisenhamer** [comment]
@jhunkeler Well, a fascinating error and that last build: apparently could not get the code. Just lettn' you know.

**Pull request merged**
