### PR TITLE
Updates to calwebb_guider processing

### PR DESCRIPTION
**Pull request by hbushouse**
First set of updates to guide star processing for #1612. The two main changes are the addition of an ERR array to the data models and a minor update to the column format of one of the table extensions (in order to match what SDP is generating). The guider_cds step has been updated to create an ERR array in the output model. Note that nothing is done yet with the ERR array at any stage of guider processing. It's just there for future expansion and to make it consistent with the SCI, DQ, ERR contents of science products.

Many other changes were made just for general cleanup and to get pep8/flake8 off my back. All of the changes to dq_init are for this purpose only, with no actual changes to the processing.

### CODE REVIEW

**Comment by dmggh** [comment]
In guider_cal.schema.yaml, isn't 'ndim: 3' needed in :   

err:
      title: Error array
      fits_hdu: ERR
      default: 0.0
      datatype: float32

and in guider_raw.schema.yaml, shouldn't there be 'ndim: 4' ?

**Comment by hbushouse** [comment]
You're right that the ERR array is 4D in the raw and 3D in the cal, and it wouldn't hurt to explicitly specify that in the schema, but it's not required in order to get them to come out that way. In the raw model the ERR array will always be created by the data model infrastructure to have the same dimensions as the SCI array (which is 4D), and for the cal model we explicitly create the ERR array in the guider_cds step using the same dimensions as the SCI array (which is 3D).

**Comment by hbushouse** [comment]
Latest commit fixes #1704 by loading the input into a GuiderCalModel if the dq_init and guider_cds steps are skipped. It makes the very implicit assumption that the input has been run through those steps previously, without actually verifying that. So it could be more robust, but good enough for now to handle this relatively obscure corner case (IMHO).

**Comment by dmggh** [comment]
This looks good to me. It might be helpful to also issue a log info statement that those steps are being skipped.

**Comment by hbushouse** [comment]
The steps themselves will send that log message. The skip operation is a bit unusual in that the step still gets called, but then immediately issues a message saying that it's being skipped and returns the input unchanged.

**Comment by dmggh** [comment]
Yes, I realize that the individual steps would each give that message, which should be apparent to the user. I was just suggesting an additional statement making it blatantly (over-) obvious to the casual user what was happening, in case that was not what they were expecting.

**Comment by hbushouse** [comment]
Latest commit applies the flat to the ERR array, now that we've implemented an ERR array in the guide star data models.

**Comment by hbushouse** [comment]
These are all of the changes needed in the near term, so merging now.

**Pull request merged**
