### PR TITLE
Fix association tests to run under new configuration

### PR DESCRIPTION
**Pull request by stscieisenhamer**

### CODE REVIEW

**Comment by jhunkeler** [comment]
@stscieisenhamer This definitely fixes up the test failures, but I noticed a typo in one of the csv filenames:

```
./jwst/associations/tests/data/jw82600_002_20151107t165901_pool.csv
                                                   ^ should be upper-case
```

We should merge this after the file has been renamed 👍

**Comment by stscieisenhamer** [comment]
@jhunkeler Nope, that is correct. Standards have changed mid-stream, and file names are expected to be all lowercase. The actual test is to accept either, because the generator is a user-level tool, and who knows what a user will do. :-)

**Comment by nden** [comment]
@stscieisenhamer This may be a real error as the test is looking for a upper case file name and can't find the file. I see the same problem in #58 test reports. When you gat a chance could you take a look at #58.

**Comment by stscieisenhamer** [comment]
Ahhh yes. Bit by two things: OS X HFS+ behavior and the last test I saw had other errors and I never went back to see the refreshed build.  Fixing momentarily...

**Comment by stscieisenhamer** [comment]
Resolved by PR #60

**Pull request merged**
