### PR TITLE
fix processing of nirspec mode NRS_BRIGHTOBJ

### LINKED ISSUE #463: Assign_wcs issue with slit_wcs compatible exp_types
As part of the recent assign_wcs overhaul for missing exp_types,  some new types were equated with slit_wcs.  There's top level logic that is still shunting those types into the "unsupported" exception since the types aren't listed along with NRS_FIXEDSLIT in get_open_slits().

### PR DESCRIPTION
**Pull request by nden**
Closes #463 

`NRS_BRIGHTOBJ` mode is a time series mode resttricted to `S1600A1`.

Also added processing of `NRS_LAMP` with all fixed slits opened. This has to be confirmed by the ins team and possibly changed.

### CODE REVIEW

**Comment by hbushouse** [comment]
I think this routine might need some additional updates to handle "normal" NRS_FIXEDSLIT exposures that are taken using a subarray readout that only encompasses one of the slits. For example, if SUBARRAY=S200A1, then that's the only slit that we want to (or can) extract. In which case the list of open slits needs to be restricted to just that one. Otherwise, if the WCS object is setup to contain information for all 5 slits, it may cause extract_2d to try to extract regions that are off the image.

**Comment by hbushouse** [comment]
Or this that already taken care of down in the get_open_fixed_slits function?

**Comment by nden** [comment]
@hbushouse I added code to handle single slits. Will merge after tests finish.

**Comment by hbushouse** [comment]
👍

**Comment by nden** [comment]
passed on Travis

**Pull request merged**
