### PR TITLE
Fix argument swap to call of set_file_table

### LINKED ISSUE #951: spec2pipeline saying assign_wcs not done when it is
Running `Spec2Pipeline` on the MIR_MRS dataset provided by K.Murray in
```
/grp/jwst/ssb/test_build7.1/development/miri/groundtestdata/mrs
```
errors with the log below. The last message is
```
jwst.cube_build.file_table.ErrorNoAssignWCS: ('Assign WCS has not been run on file %s', <jwst.datamodels.image.ImageModel object at 0x1215a4128>)
```
`SloperPipeline` ran to completion to create the 2a files. And, as is seen in the log below, `Spec2Pipeline` claims to successfully run the `assign_wcs` step.

Could be an incomplete dataset, but putting up in case something else is happening.

Log:
```
strun ../configs/calwebb_spec2.cfg det_image_seq1_MIRIFUSHORT_12LONGexp1_rate.fits
2017-06-05 14:13:24,762 - stpipe.Spec2Pipeline - INFO - Spec2Pipeline instance created.
2017-06-05 14:13:24,763 - stpipe.Spec2Pipeline.pathloss - INFO - PathLossStep instance created.
2017-06-05 14:13:24,764 - stpipe.Spec2Pipeline.flat_field - INFO - FlatFieldStep instance created.
2017-06-05 14:13:24,764 - stpipe.Spec2Pipeline.bkg_subtract - INFO - BackgroundStep instance created.
2017-06-05 14:13:24,765 - stpipe.Spec2Pipeline.resample_spec - INFO - ResampleSpecStep instance created.
2017-06-05 14:13:24,767 - stpipe.Spec2Pipeline.cube_build - INFO - CubeBuildStep instance created.
2017-06-05 14:13:24,767 - stpipe.Spec2Pipeline.imprint_subtract - INFO - ImprintStep instance created.
2017-06-05 14:13:24,768 - stpipe.Spec2Pipeline.photom - INFO - PhotomStep instance created.
2017-06-05 14:13:24,768 - stpipe.Spec2Pipeline.extract_1d - INFO - Extract1dStep instance created.
2017-06-05 14:13:24,769 - stpipe.Spec2Pipeline.srctype - INFO - SourceTypeStep instance created.
2017-06-05 14:13:24,770 - stpipe.Spec2Pipeline.assign_wcs - INFO - AssignWcsStep instance created.
2017-06-05 14:13:24,770 - stpipe.Spec2Pipeline.fringe - INFO - FringeStep instance created.
2017-06-05 14:13:24,771 - stpipe.Spec2Pipeline.extract_2d - INFO - Extract2dStep instance created.
2017-06-05 14:13:24,771 - stpipe.Spec2Pipeline.straylight - INFO - StraylightStep instance created.
2017-06-05 14:13:24,772 - stpipe - INFO - Hostname: inanna2.local.stsci.edu
2017-06-05 14:13:24,772 - stpipe - INFO - OS: Darwin
2017-06-05 14:13:26,150 - stpipe.Spec2Pipeline.pathloss - INFO - Prefetch for PATHLOSS reference file is 'N/A'.
2017-06-05 14:13:26,594 - stpipe.Spec2Pipeline.flat_field - INFO - Prefetch for DFLAT reference file is 'N/A'.
2017-06-05 14:13:26,594 - stpipe.Spec2Pipeline.flat_field - INFO - Prefetch for FFLAT reference file is 'N/A'.
2017-06-05 14:13:26,595 - stpipe.Spec2Pipeline.flat_field - INFO - Prefetch for FLAT reference file is '/Users/eisenham/Documents/ssbdev/testdata/crds-cache/references/jwst/miri/jwst_miri_flat_0246.fits'.
2017-06-05 14:13:26,595 - stpipe.Spec2Pipeline.flat_field - INFO - Prefetch for SFLAT reference file is 'N/A'.
2017-06-05 14:13:27,252 - stpipe.Spec2Pipeline.resample_spec - INFO - Prefetch for DRIZPARS reference file is '/Users/eisenham/Documents/ssbdev/testdata/crds-cache/references/jwst/miri/jwst_miri_drizpars_0001.fits'.
2017-06-05 14:13:27,711 - stpipe.Spec2Pipeline.cube_build - INFO - Prefetch for CUBEPAR reference file is '/Users/eisenham/Documents/ssbdev/testdata/crds-cache/references/jwst/miri/jwst_miri_cubepar_0001.fits'.
2017-06-05 14:13:27,711 - stpipe.Spec2Pipeline.cube_build - INFO - Prefetch for RESOL reference file is '/Users/eisenham/Documents/ssbdev/testdata/crds-cache/references/jwst/miri/jwst_miri_resol_0003.fits'.
2017-06-05 14:13:28,368 - stpipe.Spec2Pipeline.photom - INFO - Prefetch for AREA reference file is 'N/A'.
2017-06-05 14:13:28,368 - stpipe.Spec2Pipeline.photom - INFO - Prefetch for PHOTOM reference file is '/Users/eisenham/Documents/ssbdev/testdata/crds-cache/references/jwst/miri/jwst_miri_photom_0018.fits'.
2017-06-05 14:13:28,824 - stpipe.Spec2Pipeline.extract_1d - INFO - Prefetch for EXTRACT1D reference file is '/Users/eisenham/Documents/ssbdev/testdata/crds-cache/references/jwst/miri/jwst_miri_extract1d_0003.json'.
2017-06-05 14:13:29,465 - stpipe.Spec2Pipeline.assign_wcs - INFO - Prefetch for CAMERA reference file is 'N/A'.
2017-06-05 14:13:29,465 - stpipe.Spec2Pipeline.assign_wcs - INFO - Prefetch for COLLIMATOR reference file is 'N/A'.
2017-06-05 14:13:29,465 - stpipe.Spec2Pipeline.assign_wcs - INFO - Prefetch for DISPERSER reference file is 'N/A'.
2017-06-05 14:13:29,465 - stpipe.Spec2Pipeline.assign_wcs - INFO - Prefetch for DISTORTION reference file is '/Users/eisenham/Documents/ssbdev/testdata/crds-cache/references/jwst/miri/jwst_miri_distortion_0025.asdf'.
2017-06-05 14:13:29,465 - stpipe.Spec2Pipeline.assign_wcs - INFO - Prefetch for FILTEROFFSET reference file is 'N/A'.
2017-06-05 14:13:29,465 - stpipe.Spec2Pipeline.assign_wcs - INFO - Prefetch for FORE reference file is 'N/A'.
2017-06-05 14:13:29,465 - stpipe.Spec2Pipeline.assign_wcs - INFO - Prefetch for FPA reference file is 'N/A'.
2017-06-05 14:13:29,465 - stpipe.Spec2Pipeline.assign_wcs - INFO - Prefetch for IFUFORE reference file is 'N/A'.
2017-06-05 14:13:29,466 - stpipe.Spec2Pipeline.assign_wcs - INFO - Prefetch for IFUPOST reference file is 'N/A'.
2017-06-05 14:13:29,466 - stpipe.Spec2Pipeline.assign_wcs - INFO - Prefetch for IFUSLICER reference file is 'N/A'.
2017-06-05 14:13:29,466 - stpipe.Spec2Pipeline.assign_wcs - INFO - Prefetch for MSA reference file is 'N/A'.
2017-06-05 14:13:29,466 - stpipe.Spec2Pipeline.assign_wcs - INFO - Prefetch for OTE reference file is 'N/A'.
2017-06-05 14:13:29,466 - stpipe.Spec2Pipeline.assign_wcs - INFO - Prefetch for REGIONS reference file is '/Users/eisenham/Documents/ssbdev/testdata/crds-cache/references/jwst/miri/jwst_miri_regions_0018.asdf'.
2017-06-05 14:13:29,466 - stpipe.Spec2Pipeline.assign_wcs - INFO - Prefetch for SPECWCS reference file is '/Users/eisenham/Documents/ssbdev/testdata/crds-cache/references/jwst/miri/jwst_miri_specwcs_0014.asdf'.
2017-06-05 14:13:29,466 - stpipe.Spec2Pipeline.assign_wcs - INFO - Prefetch for V2V3 reference file is '/Users/eisenham/Documents/ssbdev/testdata/crds-cache/references/jwst/miri/jwst_miri_v2v3_0007.asdf'.
2017-06-05 14:13:29,466 - stpipe.Spec2Pipeline.assign_wcs - INFO - Prefetch for WAVELENGTHRANGE reference file is '/Users/eisenham/Documents/ssbdev/testdata/crds-cache/references/jwst/miri/jwst_miri_wavelengthrange_0003.asdf'.
2017-06-05 14:13:29,932 - stpipe.Spec2Pipeline.fringe - INFO - Prefetch for FRINGE reference file is '/Users/eisenham/Documents/ssbdev/testdata/crds-cache/references/jwst/miri/jwst_miri_fringe_0028.fits'.
2017-06-05 14:13:30,589 - stpipe.Spec2Pipeline.straylight - INFO - Prefetch for STRAYMASK reference file is '/Users/eisenham/Documents/ssbdev/testdata/crds-cache/references/jwst/miri/jwst_miri_straymask_0004.fits'.
2017-06-05 14:13:30,661 - stpipe.Spec2Pipeline - INFO - Step Spec2Pipeline running with args ('det_image_seq1_MIRIFUSHORT_12LONGexp1_rate.fits',).
2017-06-05 14:13:30,661 - stpipe.Spec2Pipeline - INFO - Starting calwebb_spec2 ...
2017-06-05 14:13:30,699 - stpipe.Spec2Pipeline - INFO - Processing product det_image_seq1_MIRIFUSHORT_12LONGexp1
2017-06-05 14:13:30,699 - stpipe.Spec2Pipeline - INFO - Working on input det_image_seq1_MIRIFUSHORT_12LONGexp1_rate.fits ...
2017-06-05 14:13:31,076 - stpipe.Spec2Pipeline.assign_wcs - INFO - Prefetch for CAMERA reference file is 'N/A'.
2017-06-05 14:13:31,077 - stpipe.Spec2Pipeline.assign_wcs - INFO - Prefetch for COLLIMATOR reference file is 'N/A'.
2017-06-05 14:13:31,077 - stpipe.Spec2Pipeline.assign_wcs - INFO - Prefetch for DISPERSER reference file is 'N/A'.
2017-06-05 14:13:31,077 - stpipe.Spec2Pipeline.assign_wcs - INFO - Prefetch for DISTORTION reference file is '/Users/eisenham/Documents/ssbdev/testdata/crds-cache/references/jwst/miri/jwst_miri_distortion_0025.asdf'.
2017-06-05 14:13:31,077 - stpipe.Spec2Pipeline.assign_wcs - INFO - Prefetch for FILTEROFFSET reference file is 'N/A'.
2017-06-05 14:13:31,077 - stpipe.Spec2Pipeline.assign_wcs - INFO - Prefetch for FORE reference file is 'N/A'.
2017-06-05 14:13:31,077 - stpipe.Spec2Pipeline.assign_wcs - INFO - Prefetch for FPA reference file is 'N/A'.
2017-06-05 14:13:31,077 - stpipe.Spec2Pipeline.assign_wcs - INFO - Prefetch for IFUFORE reference file is 'N/A'.
2017-06-05 14:13:31,077 - stpipe.Spec2Pipeline.assign_wcs - INFO - Prefetch for IFUPOST reference file is 'N/A'.
2017-06-05 14:13:31,077 - stpipe.Spec2Pipeline.assign_wcs - INFO - Prefetch for IFUSLICER reference file is 'N/A'.
2017-06-05 14:13:31,077 - stpipe.Spec2Pipeline.assign_wcs - INFO - Prefetch for MSA reference file is 'N/A'.
2017-06-05 14:13:31,077 - stpipe.Spec2Pipeline.assign_wcs - INFO - Prefetch for OTE reference file is 'N/A'.
2017-06-05 14:13:31,077 - stpipe.Spec2Pipeline.assign_wcs - INFO - Prefetch for REGIONS reference file is '/Users/eisenham/Documents/ssbdev/testdata/crds-cache/references/jwst/miri/jwst_miri_regions_0018.asdf'.
2017-06-05 14:13:31,077 - stpipe.Spec2Pipeline.assign_wcs - INFO - Prefetch for SPECWCS reference file is '/Users/eisenham/Documents/ssbdev/testdata/crds-cache/references/jwst/miri/jwst_miri_specwcs_0014.asdf'.
2017-06-05 14:13:31,077 - stpipe.Spec2Pipeline.assign_wcs - INFO - Prefetch for V2V3 reference file is '/Users/eisenham/Documents/ssbdev/testdata/crds-cache/references/jwst/miri/jwst_miri_v2v3_0007.asdf'.
2017-06-05 14:13:31,077 - stpipe.Spec2Pipeline.assign_wcs - INFO - Prefetch for WAVELENGTHRANGE reference file is '/Users/eisenham/Documents/ssbdev/testdata/crds-cache/references/jwst/miri/jwst_miri_wavelengthrange_0003.asdf'.
2017-06-05 14:13:31,113 - stpipe.Spec2Pipeline.assign_wcs - INFO - Step assign_wcs running with args (<jwst.datamodels.image.ImageModel object at 0x11d804630>,).
2017-06-05 14:13:40,814 - stpipe.Spec2Pipeline.assign_wcs - INFO - COMPLETED assign_wcs
2017-06-05 14:13:41,079 - stpipe.Spec2Pipeline.assign_wcs - INFO - Step assign_wcs done
2017-06-05 14:13:43,361 - stpipe.Spec2Pipeline.flat_field - INFO - Prefetch for DFLAT reference file is 'N/A'.
2017-06-05 14:13:43,361 - stpipe.Spec2Pipeline.flat_field - INFO - Prefetch for FFLAT reference file is 'N/A'.
2017-06-05 14:13:43,361 - stpipe.Spec2Pipeline.flat_field - INFO - Prefetch for FLAT reference file is '/Users/eisenham/Documents/ssbdev/testdata/crds-cache/references/jwst/miri/jwst_miri_flat_0246.fits'.
2017-06-05 14:13:43,361 - stpipe.Spec2Pipeline.flat_field - INFO - Prefetch for SFLAT reference file is 'N/A'.
2017-06-05 14:13:43,491 - stpipe.Spec2Pipeline.flat_field - INFO - Step flat_field running with args (<jwst.datamodels.image.ImageModel object at 0x1133868d0>,).
2017-06-05 14:13:45,640 - stpipe.Spec2Pipeline.flat_field - WARNING - Keyword CDP_LOW_QUAL does not correspond to an existing DQ mnemonic, so will be ignored
2017-06-05 14:13:46,433 - stpipe.Spec2Pipeline.flat_field - WARNING - /Users/eisenham/anaconda3/envs/spec3/lib/python3.5/site-packages/jwst-0.7.7.dev756-py3.5-macosx-10.7-x86_64.egg/jwst/flatfield/flat_field.py:193: RuntimeWarning: divide by zero encountered in true_divide
  science.data /= flat_data

2017-06-05 14:13:46,568 - stpipe.Spec2Pipeline.flat_field - WARNING - /Users/eisenham/anaconda3/envs/spec3/lib/python3.5/site-packages/jwst-0.7.7.dev756-py3.5-macosx-10.7-x86_64.egg/jwst/flatfield/flat_field.py:194: RuntimeWarning: divide by zero encountered in true_divide
  science.err /= flat_data

2017-06-05 14:13:47,174 - stpipe.Spec2Pipeline.flat_field - INFO - Step flat_field done
2017-06-05 14:13:47,546 - stpipe.Spec2Pipeline.srctype - INFO - Step srctype running with args (<jwst.datamodels.image.ImageModel object at 0x11d808d68>,).
2017-06-05 14:13:48,334 - stpipe.Spec2Pipeline.srctype - INFO - Input EXP_TYPE is MIR_MRS
2017-06-05 14:13:48,334 - stpipe.Spec2Pipeline.srctype - INFO - Input SRCTYPE is unknown. Setting to default value of EXTENDED
2017-06-05 14:13:48,604 - stpipe.Spec2Pipeline.srctype - INFO - Step srctype done
2017-06-05 14:13:50,672 - stpipe.Spec2Pipeline.straylight - INFO - Prefetch for STRAYMASK reference file is '/Users/eisenham/Documents/ssbdev/testdata/crds-cache/references/jwst/miri/jwst_miri_straymask_0004.fits'.
2017-06-05 14:13:50,797 - stpipe.Spec2Pipeline.straylight - INFO - Step straylight running with args (<jwst.datamodels.image.ImageModel object at 0x1187cb128>,).
2017-06-05 14:13:52,801 - stpipe.Spec2Pipeline.straylight - INFO - Using STRAYLIGHT reference file /Users/eisenham/Documents/ssbdev/testdata/crds-cache/references/jwst/miri/jwst_miri_straymask_0004.fits
2017-06-05 14:14:04,461 - stpipe.Spec2Pipeline.straylight - INFO - Step straylight done
2017-06-05 14:14:06,673 - stpipe.Spec2Pipeline.fringe - INFO - Prefetch for FRINGE reference file is '/Users/eisenham/Documents/ssbdev/testdata/crds-cache/references/jwst/miri/jwst_miri_fringe_0028.fits'.
2017-06-05 14:14:06,812 - stpipe.Spec2Pipeline.fringe - INFO - Step fringe running with args (<jwst.datamodels.image.ImageModel object at 0x11d7ecbe0>,).
2017-06-05 14:14:08,985 - stpipe.Spec2Pipeline.fringe - INFO - Using FRINGE reference file: /Users/eisenham/Documents/ssbdev/testdata/crds-cache/references/jwst/miri/jwst_miri_fringe_0028.fits
2017-06-05 14:14:09,051 - stpipe.Spec2Pipeline.fringe - WARNING - Keyword CDP_PARTIAL_DATA does not correspond to an existing DQ mnemonic, so will be ignored
2017-06-05 14:14:09,051 - stpipe.Spec2Pipeline.fringe - WARNING - Keyword CDP_LOW_QUAL does not correspond to an existing DQ mnemonic, so will be ignored
2017-06-05 14:14:09,051 - stpipe.Spec2Pipeline.fringe - WARNING - Keyword CDP_UNRELIABLE_ERROR does not correspond to an existing DQ mnemonic, so will be ignored
2017-06-05 14:14:09,927 - stpipe.Spec2Pipeline.fringe - INFO - The DQ values in the reference file will NOT be used to update the    DQ values in the output DQ array.
2017-06-05 14:14:10,198 - stpipe.Spec2Pipeline.fringe - INFO - Step fringe done
2017-06-05 14:14:12,360 - stpipe.Spec2Pipeline.photom - INFO - Prefetch for AREA reference file is 'N/A'.
2017-06-05 14:14:12,360 - stpipe.Spec2Pipeline.photom - INFO - Prefetch for PHOTOM reference file is '/Users/eisenham/Documents/ssbdev/testdata/crds-cache/references/jwst/miri/jwst_miri_photom_0018.fits'.
2017-06-05 14:14:12,498 - stpipe.Spec2Pipeline.photom - INFO - Step photom running with args (<jwst.datamodels.image.ImageModel object at 0x1218ccb00>,).
2017-06-05 14:14:14,503 - stpipe.Spec2Pipeline.photom - INFO - Using photom reference file: /Users/eisenham/Documents/ssbdev/testdata/crds-cache/references/jwst/miri/jwst_miri_photom_0018.fits
2017-06-05 14:14:15,746 - stpipe.Spec2Pipeline.photom - INFO - Using area reference file: N/A
2017-06-05 14:14:15,746 - stpipe.Spec2Pipeline.photom - INFO - Using instrument: MIRI
2017-06-05 14:14:15,746 - stpipe.Spec2Pipeline.photom - INFO -  detector: MIRIFUSHORT
2017-06-05 14:14:15,746 - stpipe.Spec2Pipeline.photom - INFO -  exp_type: MIR_MRS
2017-06-05 14:14:15,746 - stpipe.Spec2Pipeline.photom - INFO -  band: LONG
2017-06-05 14:14:15,830 - stpipe.Spec2Pipeline.photom - WARNING - Keyword CDP_LOW_QUAL does not correspond to an existing DQ mnemonic, so will be ignored
2017-06-05 14:14:16,769 - stpipe.Spec2Pipeline.photom - INFO - Writing PHOTMJSR with value: 42.5
2017-06-05 14:14:17,081 - stpipe.Spec2Pipeline.photom - INFO - Step photom done
2017-06-05 14:14:19,272 - stpipe.Spec2Pipeline.cube_build - INFO - Prefetch for CUBEPAR reference file is '/Users/eisenham/Documents/ssbdev/testdata/crds-cache/references/jwst/miri/jwst_miri_cubepar_0001.fits'.
2017-06-05 14:14:19,273 - stpipe.Spec2Pipeline.cube_build - INFO - Prefetch for RESOL reference file is '/Users/eisenham/Documents/ssbdev/testdata/crds-cache/references/jwst/miri/jwst_miri_resol_0003.fits'.
2017-06-05 14:14:19,396 - stpipe.Spec2Pipeline.cube_build - INFO - Step cube_build running with args (<jwst.datamodels.image.ImageModel object at 0x1215a4128>,).
2017-06-05 14:14:19,396 - stpipe.Spec2Pipeline.cube_build - INFO - Starting IFU Cube Building Step
2017-06-05 14:14:19,396 - stpipe.Spec2Pipeline.cube_build - INFO - Input interpolation: pointcloud
2017-06-05 14:14:19,396 - stpipe.Spec2Pipeline.cube_build - INFO - Coordinate system to use: ra-dec
2017-06-05 14:14:19,396 - stpipe.Spec2Pipeline.cube_build - INFO - Weighting method for point cloud: standard
2017-06-05 14:14:19,396 - stpipe.Spec2Pipeline.cube_build - INFO - Power Weighting distance : 2.000000
----------------------------------------------------------------------
ERROR RUNNING STEP 'Spec2Pipeline':
    ('Assign WCS has not been run on file %s',
    <jwst.datamodels.image.ImageModel object at 0x1215a4128>)
Traceback (most recent call last):
  File "/Users/eisenham/anaconda3/envs/spec3/lib/python3.5/site-packages/jwst-0.7.7.dev756-py3.5-macosx-10.7-x86_64.egg/jwst/stpipe/cmdline.py", line 320, in step_from_cmdline
    step.run(*positional)
  File "/Users/eisenham/anaconda3/envs/spec3/lib/python3.5/site-packages/jwst-0.7.7.dev756-py3.5-macosx-10.7-x86_64.egg/jwst/stpipe/step.py", line 356, in run
    result = self.process(*args)
  File "/Users/eisenham/anaconda3/envs/spec3/lib/python3.5/site-packages/jwst-0.7.7.dev756-py3.5-macosx-10.7-x86_64.egg/jwst/pipeline/calwebb_spec2.py", line 94, in process
    asn.filename
  File "/Users/eisenham/anaconda3/envs/spec3/lib/python3.5/site-packages/jwst-0.7.7.dev756-py3.5-macosx-10.7-x86_64.egg/jwst/pipeline/calwebb_spec2.py", line 249, in process_exposure_product
    cube = self.cube_build(input)
  File "/Users/eisenham/anaconda3/envs/spec3/lib/python3.5/site-packages/jwst-0.7.7.dev756-py3.5-macosx-10.7-x86_64.egg/jwst/stpipe/step.py", line 356, in run
    result = self.process(*args)
  File "/Users/eisenham/anaconda3/envs/spec3/lib/python3.5/site-packages/jwst-0.7.7.dev756-py3.5-macosx-10.7-x86_64.egg/jwst/cube_build/cube_build_step.py", line 202, in process
    self.output_file = cubeinfo.setup()
  File "/Users/eisenham/anaconda3/envs/spec3/lib/python3.5/site-packages/jwst-0.7.7.dev756-py3.5-macosx-10.7-x86_64.egg/jwst/cube_build/cube_build.py", line 159, in setup
    self.dec_offset)
  File "/Users/eisenham/anaconda3/envs/spec3/lib/python3.5/site-packages/jwst-0.7.7.dev756-py3.5-macosx-10.7-x86_64.egg/jwst/cube_build/file_table.py", line 211, in set_file_table
    ifile)
jwst.cube_build.file_table.ErrorNoAssignWCS: ('Assign WCS has not been run on file %s', <jwst.datamodels.image.ImageModel object at 0x1215a4128>)

----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/eisenham/anaconda3/envs/spec3/lib/python3.5/site-packages/jwst-0.7.7.dev756-py3.5-macosx-10.7-x86_64.egg/EGG-INFO/scripts/strun", line 14, in <module>
    step = Step.from_cmdline(sys.argv[1:])
  File "/Users/eisenham/anaconda3/envs/spec3/lib/python3.5/site-packages/jwst-0.7.7.dev756-py3.5-macosx-10.7-x86_64.egg/jwst/stpipe/step.py", line 142, in from_cmdline
    return cmdline.step_from_cmdline(args)
  File "/Users/eisenham/anaconda3/envs/spec3/lib/python3.5/site-packages/jwst-0.7.7.dev756-py3.5-macosx-10.7-x86_64.egg/jwst/stpipe/cmdline.py", line 320, in step_from_cmdline
    step.run(*positional)
  File "/Users/eisenham/anaconda3/envs/spec3/lib/python3.5/site-packages/jwst-0.7.7.dev756-py3.5-macosx-10.7-x86_64.egg/jwst/stpipe/step.py", line 356, in run
    result = self.process(*args)
  File "/Users/eisenham/anaconda3/envs/spec3/lib/python3.5/site-packages/jwst-0.7.7.dev756-py3.5-macosx-10.7-x86_64.egg/jwst/pipeline/calwebb_spec2.py", line 94, in process
    asn.filename
  File "/Users/eisenham/anaconda3/envs/spec3/lib/python3.5/site-packages/jwst-0.7.7.dev756-py3.5-macosx-10.7-x86_64.egg/jwst/pipeline/calwebb_spec2.py", line 249, in process_exposure_product
    cube = self.cube_build(input)
  File "/Users/eisenham/anaconda3/envs/spec3/lib/python3.5/site-packages/jwst-0.7.7.dev756-py3.5-macosx-10.7-x86_64.egg/jwst/stpipe/step.py", line 356, in run
    result = self.process(*args)
  File "/Users/eisenham/anaconda3/envs/spec3/lib/python3.5/site-packages/jwst-0.7.7.dev756-py3.5-macosx-10.7-x86_64.egg/jwst/cube_build/cube_build_step.py", line 202, in process
    self.output_file = cubeinfo.setup()
  File "/Users/eisenham/anaconda3/envs/spec3/lib/python3.5/site-packages/jwst-0.7.7.dev756-py3.5-macosx-10.7-x86_64.egg/jwst/cube_build/cube_build.py", line 159, in setup
    self.dec_offset)
  File "/Users/eisenham/anaconda3/envs/spec3/lib/python3.5/site-packages/jwst-0.7.7.dev756-py3.5-macosx-10.7-x86_64.egg/jwst/cube_build/file_table.py", line 211, in set_file_table
    ifile)
jwst.cube_build.file_table.ErrorNoAssignWCS: ('Assign WCS has not been run on file %s', <jwst.datamodels.image.ImageModel object at 0x1215a4128>)
```

### PR DESCRIPTION
**Pull request by stscieisenhamer**
Resolves #951 

Apologies for the bazillion diffs; emacs fixes all.

The relevant diff is in file `cube_build.py` line 156: Arguments to `set_file_table` had the models and filenames swapped.

### CODE REVIEW

**Comment by nden** [comment]
:+1:  Pretty sure that this will also fix #954

**Comment by jemorrison** [comment]
Yes it looks like I switched the order of models and filenames -
let me switch this on my test code and test it the various ways cube build can be run

**Comment by stscieisenhamer** [comment]
@jemorrison wow hope that is automated...seems to be quite the list of scenarios..."cube build here, cube-build there, cube-build cube-build cube-build everywhere...old MacDonald had some data...eieioooooo"

**Comment by jemorrison** [comment]
It is sort of automated - I have a set of python codes that I run but not one file that runs everything. I should eventually do that. But it really is a book keeping thing and I lose track if I don't run each "type" of cube to build individually.

**Comment by stscieisenhamer** [comment]
ok, so [much wow](http://vignette3.wikia.nocookie.net/asteria-eng/images/4/44/Such-wow-much-doge.png/revision/latest?cb=20160223010550)...The same test fails in all four configurations. However, three fail with error message about undefined argument `bounding_box` and one fails with undefined argument `fill_value`.  And, of course, tests succeed locally.

And, as far as I can tell, all are unrelated to the actual commit. Sooooo, am merging.

**Pull request merged**
