### PR TITLE
Activate WFSS background subtraction

### LINKED ISSUE #1917: Activate WFSS background subtraction
CRDS context 450 now includes WFSSBKG reference files for both NIRCam and NIRISS, so background subtraction of WFSS exposures can now be activated in the cal pipeline.

### PR DESCRIPTION
**Pull request by hbushouse**
Update the background_subtraction step to activate the loading and subtracting of WFSSBKG reference images for WFSS exposures. This simply involves uncommenting lines that were already included in the routine, but were waiting for the ref files to become available.

Fixes #1917.

### CODE REVIEW

**Comment by sosey** [comment]
This PR also has the changes in it: #1832

**Comment by hbushouse** [comment]
I had forgotten that you had already created #1832. I was thinking you had only made the changes in a local branch, but was not in a PR. They both look functionally equivalent (only real difference is that I added a couple of log messages). So I guess #1832 could be closed.

By the way, I have tested and confirmed that it all works correctly for non-WFSS and imaging exposures too (using calwebb_image2), in that the CRDS rmaps contain all the correct N/A entries for those modes.

**Comment by hbushouse** [comment]
I tested this PR on both NIRISS and NIRCam WFSS exposures and background subtraction worked fine for both.

**Comment by philhodge** [comment]
Both this PR and #1832 look fine to me.

**Comment by hbushouse** [comment]
Merging to get into tonight's build and regression test run.

**Pull request merged**
