### PR TITLE
Port and initial implementation of exp_to_source

### LINKED ISSUE #158: Exposure to Source tool
Simple utility to take exposure-based data, in particular datamodel.MultiSlitModel, and re-arrange into souce-based data, similar in structure to datamodel.MultiSlitModel.

### PR DESCRIPTION
**Pull request by stscieisenhamer**
Port of exp_to_exposure from the SVN; not done because this was still in a branch.
New model MultiExposureModel comes for free.

@hbushouse Ready for review.

Resolves #158

### CODE REVIEW

**Comment by stscieisenhamer** [comment]
@jhunkeler None of these errors are mine. Don't know what's up.

**Comment by hbushouse** [comment]
I've never seen any of these types of failures before in the Travis tests. Is there a way to kick them off again just to see if it was some kind of fluke on the first attempt?

**Comment by hbushouse** [comment]
I worry about having the schema file "core_exposures.schema.yaml", which is just a copy (with slight mods?) of the "core.schema.yaml" file and hence will rapidly become out of sync with "core.schema.yaml". In fact it must already be out of sync, because I've made a few changes to the core in just the past couple days. We'll need to revisit how to handle the meta data.

**Comment by stscieisenhamer** [comment]
@hbushouse I've restarted the build. I was not concerned about any of these, because none of them had anything to do with this PR. I've never had a build go successfully, and it is always for some unrelated reason, and always a different unrelated reason. We'll see what happens.

FYI: You can, usually, restart a build by going to the `Details` link. On that Travis page, in the right corner of the overall status box, you should see a circle-arrow button. This restarts the build. If you look now when a build is in progress, it will be an circle-X.

**Comment by stscieisenhamer** [comment]
@hbushouse Actually no: the schema is dynamically built so it keeps in sync with core.schema. And, I believe the following is true, since the use of the schema is no longer **strict**, when reading in existing MultiExposure files which have some previous core.schema should work fine.

**Comment by stscieisenhamer** [comment]
@hbushouse At least there are real errors now...working...

**Comment by stscieisenhamer** [comment]
@hbushouse Ahhh, but some update has broken the test files I am using. Do you have updated ones?

**Comment by hbushouse** [comment]
What kind of test files do you need?

And why are tests in jwst/transforms failing here, when they don't fail for other PR's. This PR has nothing to do with jwst/transforms.

**Comment by stscieisenhamer** [comment]
FIrst: You had given me 3 MultiSlitModel files, which are now failing loading.

About the transforms failure: I really don't know. However, since these are not part of the PR, they are ignorable. But, I do not understand why these happen. Everytime there is a PR, there is some sort of unrelated errors. They are different everytime. @jhunkeler might have a clue.

**Comment by nden** [comment]
We should try to keep the number of data files in the repository and their size as small as possible.
Is it really necessary to have three different files for the tests with all the extensions that they currently have? I don't understand what is being tests so it may very well be that all these files are needed in their present form. But if not, consider using files with the minimum size, e.g. remove extensions that are not relevant for the test. And use _compressed_ files.

**Comment by nden** [comment]
I don't think at this point we should see unrelated failures in the tests.

**Comment by hbushouse** [comment]
You can find relatively new copies of what I think are the same test files that I gave you before in /grp/jwst/ssb/bushouse/jwst_data/NIRSpec/FS/jwst_nod1_cal.fits, jwst_nod2_cal.fits, and jwst_nod3_cal.fits. I can successfully load those into a MultiSlitModel.

**Comment by larrybradley** [comment]
For the record, occasionally you will see unrelated transient failures because of some issue with `travis-ci`.  For those, simply restart the test.

**Comment by stscieisenhamer** [comment]
@nden Agree on the data. Had already discussed with @jhunkeler and do plan/awaiting on the plan on how to handle

@hbushouse Thanks! Will try the new filesets.

**Comment by stscieisenhamer** [comment]
@hbushouse well, bad news, when you update to jwst/master, these files will fail, as found in the travis run. I can fix for my purposes; just FYI

**Comment by hbushouse** [comment]
Are you saying that there's a problem with this version of exp_to_source that will make it fail if I try to run it on the same input files that successfully went through the version of exp_to_source that I installed from your branch this morning?

**Comment by stscieisenhamer** [comment]
No, the core schema has changed. In fact, it was the last PR you did: d662afff1456faf0590c922a30fad551e469e8bc

**Comment by hbushouse** [comment]
Oh sure, blame it on me! ;-)

It may be choking because the core schema changed data types for a few keywords, which are probably now throwing errors when trying to load the FITS files into a data model. I'll verify that and produce new copies of the test FITS files that have the offending keyword values modified.

**Comment by hbushouse** [comment]
OK, I modified the keywords in those 3 test FITS files, which now load OK into a datamodel. The updated versions are in the same location as before. Try 'em again.

**Comment by stscieisenhamer** [comment]
👍

**Comment by hbushouse** [comment]
Does anyone have any ideas as to why so many of the Travis tests from PR's that were submitted yesterday are still running? It's not just this one.

**Comment by stscieisenhamer** [comment]
https://www.traviscistatus.com/

Something happened with OS X builds...

**Comment by nden** [comment]
This probably explains the failed tests as well. Most of the failures are time out http server problems.

**Comment by stscieisenhamer** [comment]
Aborting this one. New one shortly.

**Pull request closed without merging**
