### PR TITLE
TST: Testing against astropy-dev is now allowed to fail

### PR DESCRIPTION
**Pull request by pllim**
This should hopefully fix the failures. xref astropy/ci-helpers#255

c/c @stscieisenhamer @jaytmiller @drdavella

### CODE REVIEW

**Comment by pllim** [comment]
A simple pip uninstall did not work. I knew that was too easy!

**Comment by pllim** [comment]
Okay I think the hack is working. The build that matters passed and I cancelled the rest. Do you want me to squash and run full test suite, which only makes sense if you plan to merge this?

**Comment by stscieisenhamer** [comment]
Merge the uninstall? Until the permanent fix is available, this looks good to me.

**Comment by pllim** [comment]
Okie dokie. I'll squash when I can get in front of a computer again.

**Comment by pllim** [comment]
@stscieisenhamer , change of plans... I updated https://github.com/STScI-JWST/jwst/pull/1446#issuecomment-343310804 to explain.

**Comment by nden** [comment]
@pllim But then we have to remember to enable it again as we _do_ test against master. Isn't the fix ready now, as in there's a PR - astropy/pytest-remotedata#20 ?

**Comment by drdavella** [comment]
@nden the fix is ready. I just want to wait for tests to pass and then I can make a new release of `pytest-remotedata`.

This does seem like a good catalyst for the discussion about github workflows and testing against development vs stable releases.

**Comment by pllim** [comment]
You're all correct. This PR can be:

(a) A fallback if Dan got distracted by other work and can't do a release soon.
(b) If you really, really want your tests to pass in the next hour (or so) before the release is made.

**Comment by pllim** [comment]
OK @drdavella fixed `remotedata` upstream, so this should be unnecessary now.

**Pull request closed without merging**
