### PR TITLE
Rename tso_photometry product name to '_phot'

### PR DESCRIPTION
**Pull request by larrybradley**
Partially addresses #991.

### CODE REVIEW

**Comment by larrybradley** [comment]
@hbushouse This step is also currently *appending* `_phot` to the existing name.  Should `_phot` replace the previous product name, and if so, what is that name?

**Comment by hbushouse** [comment]
The input to the calwebb_tso3 pipeline will be a _calints.fits product, which is a 3D cube model. The first step of the pipeline will be outlier_detection, which will result in an updated version of the input model that has additional DQ flags set. This updated model will be saved as a new product that will use a _crfints (CR-Flagged) product type extension. But if the pipeline flow is constructed in such a way that the updated model is simply passed (in memory) to the tso_photometry step, then the meta data for that model would still contain a filename attribute that uses the _calints suffix. So I would assume _calints for now and if we need to we can always update to _crfints. And yes, the suffix should be _replaced_, rather than just appending _phot.

**Comment by larrybradley** [comment]
In that case I'll make `_phot` replace both `_calints` and `_crfints` product names.

**Comment by hbushouse** [comment]
👍

**Pull request merged**
