### PR TITLE
Added COMPLETED to cube_build status

### PR DESCRIPTION
**Pull request by jemorrison**
added to core schema cal_step.cube_build with fits_keyword = S_IFUCUB
updated cube_build code to write this out to every output product produced by  cube_build

@hbushouse 
@stscieisenhamer

### CODE REVIEW

**Comment by stscieisenhamer** [comment]
Hmmmm, not sure. @nden might have some thoughts on this?  In the meantime, I'll fetch this and see if I can reproduce.

**Comment by stscieisenhamer** [comment]
Well, works fine on my end. I believe this means that something else in your branch is out-of-date with-respect-to an external library, guessing gwcs?

Considering that the commit contains nothing that is related to the error, I would go ahead and merge.

**Comment by nden** [comment]
It's coming from astropy.modeling. Are we sure the latest version of astropy is used in conda-dev?

**Comment by nden** [comment]
Just to make it clear, there's nothing wrong with this branch or PR but it looks like conda-dev has an older version of astropy. This particular change in astropy was made yesterday so it should have shown up in today's build. Not sure how to check though as Travis doesn't list the version of astropy.

**Comment by hbushouse** [comment]
👍

**Comment by nden** [comment]
@jhunkeler Can you confirm that conda-dev is using the latest astropy master ?

**Pull request merged**
