### PR TITLE
Remove extraneous spherical_geometry occurence

### PR DESCRIPTION
**Pull request by mcara**
Fixes error introduced in https://github.com/STScI-JWST/jwst/issues/1858

CC: @stsci-hack @pllim @hbushouse

### CODE REVIEW

**Comment by hbushouse** [comment]
**_NO MERGING_** until Travis completes successfully.

**Comment by pllim** [comment]
p.s. @hbushouse -- There is a repo setting to disable merge unless CI passes. FYI. However, the downside of this setting is that any PR with `[skip ci]` in commit (e.g., a simple comment line typo fix) will also be forbidden.

**Comment by mcara** [comment]
I have asked @rendinam to notify us when astroconda was rebuild with the new `spherical_geometry` package so that @hbushouse could restart the failing test.

**Comment by rendinam** [comment]
Bit of chicken-and-egg here. The package cannot be built successfully without incorporating this correction. Is it possible to merge this one-line fix so that the package can be rebuilt?

**Comment by mcara** [comment]
@rendinam I would say yes but I am afraid of @hbushouse

**Comment by pllim** [comment]
Or... Publish `spherical_geometry` in PyPI and use `pip install`? :grimacing:

**Pull request merged**
