### PR TITLE
Cube build parity

### PR DESCRIPTION
**Pull request by jemorrison**
Fix the IFU cubes parity that I messed up a few months ago.
PC1_1 = -1 is still used but the naxis1 dimension is constructed opposite what is was. 
The naxis1 dimension now increase in the opposite direction as ra does. 

For regression testing we need to establish a new reference IFU cube.

### CODE REVIEW

**Comment by jemorrison** [comment]
addresses #1895

**Comment by drlaw1558** [comment]
Doesn't there need to be a xi=-xi added into std2radec as well in order to keep the forward and backward transforms consistent?

**Comment by jemorrison** [comment]
Yes good check David. I made that change and will make a pull request soon. It only breaks things when we go backwards which would be for blotting - outlier detection.

**Comment by hbushouse** [comment]
Sorry for jumping the gun on merging last night. Glad @drlaw1558 caught that.

**Pull request merged**
