### PR TITLE
Nirspec: 1- vs 0- based pixel coordinates

### PR DESCRIPTION
**Pull request by nden**
Related to #1781. Implements the chnage in one place - ~assign_wcs.nirspec.detector_to_gwa()`

### CODE REVIEW

**Comment by nden** [comment]
@drdavella Could you take a look at the test failures? Are they related to recent changes in the history of extensions in asdf?

**Comment by nden** [comment]
@hbushouse Yes, I intend to do a final clean up of the code, once things stabilize.

**Comment by drdavella** [comment]
@nden yes these all appear to be related to the recent ASDF changes. They should all be fixed once #1833 is merged.

**Comment by drdavella** [comment]
If you want to rerun the tests, this can now be rebased on `master` since #1833 just got merged.

**Comment by nden** [comment]
Hm, didn't need to rebase. Just ran the tests again.

**Comment by hbushouse** [comment]
Regression tests have been too good for too long, so I'm merging, just to mess things up.

**Pull request merged**
