### PR TITLE
Fix NIRSpec resampling output frame

### LINKED ISSUE #1006: resample_spec index error on MIRI LRS Fixed-slit
I believe no work has been done on `resample_spec` with respect to MIRI LRS Fixed-slit, but just to document:
```
$ pytest -rsx jwst/pipeline/tests/test_calwebb_spec3_mir_lrs_fixedslit.py::test_run_resample_only --runslow
============================================================================= test session starts ==============================================================================
platform darwin -- Python 3.5.3, pytest-3.1.2, py-1.4.34, pluggy-0.4.0
rootdir: /Users/eisenham/Documents/ssbdev/jwst, inifile: setup.cfg
plugins: catchlog-1.2.2, xdist-1.16.0
collected 7 items

jwst/pipeline/tests/test_calwebb_spec3_mir_lrs_fixedslit.py F

=================================================================================== FAILURES ===================================================================================
____________________________________________________________________________ test_run_resample_only ____________________________________________________________________________

mk_tmp_dirs = ('/var/folders/z7/hcykr_n546s_5033t9rj5d200000zj/T/tmp42cj333q', '/var/folders/z7/hcykr_n546s_5033t9rj5d200000zj/T/tmpj_zwh7y5', '/var/folders/z7/hcykr_n546s_5033t9rj5d200000zj/T/tmpuqwpcvn9')

    @runslow
    @require_bigdata
    def test_run_resample_only(mk_tmp_dirs):
        """Test resample step only."""
        tmp_current_path, tmp_data_path, tmp_config_path = mk_tmp_dirs

        asn_path = update_asn_basedir(
            path.join(DATAPATH, 'jw80600-a3002_20170227t160430_spec3_001_asn.json'),
            root=DATAPATH
        )
        args = [
            path.join(SCRIPT_DATA_PATH, 'calwebb_spec3_default.cfg'),
            asn_path,
            '--steps.skymatch.skip=true',
            '--steps.outlier_detection.skip=true',
            '--steps.cube_build.skip=true',
            '--steps.extract_1d.skip=true',
        ]

>       Step.from_cmdline(args)

/Users/eisenham/Documents/ssbdev/jwst/jwst/pipeline/tests/test_calwebb_spec3_mir_lrs_fixedslit.py:110:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/Users/eisenham/Documents/ssbdev/jwst/jwst/stpipe/step.py:143: in from_cmdline
    return cmdline.step_from_cmdline(args)
/Users/eisenham/Documents/ssbdev/jwst/jwst/stpipe/cmdline.py:320: in step_from_cmdline
    step.run(*positional)
/Users/eisenham/Documents/ssbdev/jwst/jwst/stpipe/step.py:361: in run
    result = self.process(*args)
/Users/eisenham/Documents/ssbdev/jwst/jwst/pipeline/calwebb_spec3.py:127: in process
    result = self.resample_spec(result)
/Users/eisenham/Documents/ssbdev/jwst/jwst/stpipe/step.py:361: in run
    result = self.process(*args)
/Users/eisenham/Documents/ssbdev/jwst/jwst/resample/resample_spec_step.py:76: in process
    fillval=self.fillval, good_bits=self.good_bits)
/Users/eisenham/Documents/ssbdev/jwst/jwst/resample/resample_spec.py:94: in __init__
    self.build_miri_output_wcs()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <jwst.resample.resample_spec.ResampleSpecData object at 0x11c331860>
refwcs = <WCS(output_frame=world, input_frame=detector, forward_transform=Model: CompoundModel9
Inputs: ('x0', 'x1')
Outputs: (...---- -------------- ----------------
    -4.70038528245 -299.772724032 -4.70038528245 -299.772724032 0.00421921496332)>

    def build_miri_output_wcs(self, refwcs=None):
        """
            Create a simple output wcs covering footprint of the input datamodels
            """
        # TODO: generalize this for more than one input datamodel
        # TODO: generalize this for imaging modes with distorted wcs
        input_model = self.input_models[0]
        if refwcs == None:
            refwcs = input_model.meta.wcs

        x, y = wcstools.grid_from_bounding_box(refwcs.bounding_box, step=(1, 1),
            center=True)
        ra, dec, lam = refwcs(x.flatten(), y.flatten())
        # TODO: once astropy.modeling._Tabular is fixed, take out the
        # flatten() and reshape() code above and below
        ra = ra.reshape(x.shape)
        dec = dec.reshape(x.shape)
        lam = lam.reshape(x.shape)

        # Find rotation of the slit from y axis from the wcs forward transform
        # TODO: figure out if angle is necessary for MIRI.  See for discussion
        # https://github.com/STScI-JWST/jwst/pull/347
        rotation = [m for m in refwcs.forward_transform if \
            isinstance(m, Rotation2D)]
        if rotation:
            rot_slit = functools.reduce(lambda x, y: x | y, rotation)
            rot_angle = rot_slit.inverse.angle.value
            unrotate = rot_slit.inverse
            refwcs_minus_rot = refwcs.forward_transform | \
                unrotate & Identity(1)
            # Correct for this rotation in the wcs
            ra, dec, lam = refwcs_minus_rot(x.flatten(), y.flatten())
            ra = ra.reshape(x.shape)
            dec = dec.reshape(x.shape)
            lam = lam.reshape(x.shape)

        # Get the slit size at the center of the dispersion
        sky_coords = SkyCoord(ra=ra, dec=dec, unit=u.deg)
        slit_coords = sky_coords[int(sky_coords.shape[0] / 2)]
        slit_angular_size = slit_coords[0].separation(slit_coords[-1])
        log.debug('Slit angular size: {0}'.format(slit_angular_size.arcsec))

        # Compute slit center from bounding_box
        dx0 = refwcs.bounding_box[0][0]
        dx1 = refwcs.bounding_box[0][1]
        dy0 = refwcs.bounding_box[1][0]
        dy1 = refwcs.bounding_box[1][1]
        slit_center_pix = (dx1 - dx0) / 2
        dispersion_center_pix = (dy1 - dy0) / 2
        slit_center = refwcs_minus_rot(dx0 + slit_center_pix, dy0 +
            dispersion_center_pix)
        slit_center_sky = SkyCoord(ra=slit_center[0], dec=slit_center[1],
            unit=u.deg)
        log.debug('slit center: {0}'.format(slit_center))

        # Compute spatial and spectral scales
        spatial_scale = slit_angular_size / slit_coords.shape[0]
        log.debug('Spatial scale: {0}'.format(spatial_scale.arcsec))
        tcenter = int((dx1 - dx0) / 2)
        trace = lam[:, tcenter]
        trace = trace[~np.isnan(trace)]
>       spectral_scale = np.abs((trace[-1] - trace[0]) / trace.shape[0])
E       IndexError: index -1 is out of bounds for axis 0 with size 0

/Users/eisenham/Documents/ssbdev/jwst/jwst/resample/resample_spec.py:321: IndexError
----------------------------------------------------------------------------- Captured stdout call -----------------------------------------------------------------------------
----------------------------------------------------------------------
ERROR RUNNING STEP 'Spec3Pipeline':
    index -1 is out of bounds for axis 0 with size 0
Traceback (most recent call last):
  File "/Users/eisenham/Documents/ssbdev/jwst/jwst/stpipe/cmdline.py", line 320, in step_from_cmdline
    step.run(*positional)
  File "/Users/eisenham/Documents/ssbdev/jwst/jwst/stpipe/step.py", line 361, in run
    result = self.process(*args)
  File "/Users/eisenham/Documents/ssbdev/jwst/jwst/pipeline/calwebb_spec3.py", line 127, in process
    result = self.resample_spec(result)
  File "/Users/eisenham/Documents/ssbdev/jwst/jwst/stpipe/step.py", line 361, in run
    result = self.process(*args)
  File "/Users/eisenham/Documents/ssbdev/jwst/jwst/resample/resample_spec_step.py", line 76, in process
    fillval=self.fillval, good_bits=self.good_bits)
  File "/Users/eisenham/Documents/ssbdev/jwst/jwst/resample/resample_spec.py", line 94, in __init__
    self.build_miri_output_wcs()
  File "/Users/eisenham/Documents/ssbdev/jwst/jwst/resample/resample_spec.py", line 321, in build_miri_output_wcs
    spectral_scale = np.abs((trace[-1] - trace[0]) / trace.shape[0])
IndexError: index -1 is out of bounds for axis 0 with size 0

----------------------------------------------------------------------
----------------------------------------------------------------------------- Captured stderr call -----------------------------------------------------------------------------
2017-06-27 09:03:38,105 - stpipe.Spec3Pipeline - INFO - Spec3Pipeline instance created.
2017-06-27 09:03:38,106 - stpipe.Spec3Pipeline.cube_build - INFO - CubeBuildStep instance created.
2017-06-27 09:03:38,107 - stpipe.Spec3Pipeline.outlier_detection - INFO - OutlierDetectionStep instance created.
2017-06-27 09:03:38,108 - stpipe.Spec3Pipeline.extract_1d - INFO - Extract1dStep instance created.
2017-06-27 09:03:38,109 - stpipe.Spec3Pipeline.skymatch - INFO - SkyMatchStep instance created.
2017-06-27 09:03:38,110 - stpipe.Spec3Pipeline.resample_spec - INFO - ResampleSpecStep instance created.
2017-06-27 09:03:38,110 - stpipe - INFO - Hostname: inanna2.local
2017-06-27 09:03:38,110 - stpipe - INFO - OS: Darwin
2017-06-27 09:03:38,172 - stpipe.Spec3Pipeline - INFO - Step Spec3Pipeline running with args ('/var/folders/z7/hcykr_n546s_5033t9rj5d200000zj/T/tmpv205aqe8.json',).
2017-06-27 09:03:38,172 - stpipe.Spec3Pipeline - INFO - Starting calwebb_spec3 ...
2017-06-27 09:03:38,700 - stpipe.Spec3Pipeline - INFO - Running on data of EXP_TYPE=MIR_LRS-FIXEDSLIT
2017-06-27 09:03:38,761 - stpipe.Spec3Pipeline.outlier_detection - INFO - Step outlier_detection running with args (<jwst.datamodels.container.ModelContainer object at 0x104f12be0>,).
2017-06-27 09:03:38,761 - stpipe.Spec3Pipeline.outlier_detection - INFO - Step skipped.
2017-06-27 09:03:38,762 - stpipe.Spec3Pipeline.outlier_detection - INFO - Step outlier_detection done
2017-06-27 09:03:38,813 - stpipe.Spec3Pipeline.resample_spec - INFO - Step resample_spec running with args (<jwst.datamodels.container.ModelContainer object at 0x104f12be0>,).
------------------------------------------------------------------------------ Captured log call -------------------------------------------------------------------------------
step.py                    289 INFO     Spec3Pipeline instance created.
step.py                    289 INFO     CubeBuildStep instance created.
step.py                    289 INFO     OutlierDetectionStep instance created.
step.py                    289 INFO     Extract1dStep instance created.
step.py                    289 INFO     SkyMatchStep instance created.
step.py                    289 INFO     ResampleSpecStep instance created.
cmdline.py                 281 INFO     Hostname: inanna2.local
cmdline.py                 281 INFO     Hostname: inanna2.local
cmdline.py                 282 INFO     OS: Darwin
cmdline.py                 282 INFO     OS: Darwin
step.py                    340 INFO     Step Spec3Pipeline running with args ('/var/folders/z7/hcykr_n546s_5033t9rj5d200000zj/T/tmpv205aqe8.json',).
calwebb_spec3.py            54 INFO     Starting calwebb_spec3 ...
util.py                    145 DEBUG    Opening as <class 'jwst.datamodels.image.ImageModel'>
util.py                    145 DEBUG    Opening as <class 'jwst.datamodels.image.ImageModel'>
util.py                    145 DEBUG    Opening as <class 'jwst.datamodels.image.ImageModel'>
util.py                    145 DEBUG    Opening as <class 'jwst.datamodels.image.ImageModel'>
calwebb_spec3.py            72 INFO     Running on data of EXP_TYPE=MIR_LRS-FIXEDSLIT
step.py                    340 INFO     Step outlier_detection running with args (<jwst.datamodels.container.ModelContainer object at 0x104f12be0>,).
step.py                    357 INFO     Step skipped.
step.py                    422 INFO     Step outlier_detection done
step.py                    340 INFO     Step resample_spec running with args (<jwst.datamodels.container.ModelContainer object at 0x104f12be0>,).
resample_spec.py           300 DEBUG    Slit angular size: nan
resample_spec.py           300 DEBUG    Slit angular size: nan
resample_spec.py           313 DEBUG    slit center: (nan, nan, nan)
resample_spec.py           313 DEBUG    slit center: (nan, nan, nan)
resample_spec.py           317 DEBUG    Spatial scale: nan
resample_spec.py           317 DEBUG    Spatial scale: nan
=============================================================================== warnings summary ===============================================================================
jwst/pipeline/tests/test_calwebb_spec3_mir_lrs_fixedslit.py::test_run_resample_only
  /Users/eisenham/anaconda3/envs/spec3/lib/python3.5/site-packages/astropy/coordinates/angles.py:625: RuntimeWarning: invalid value encountered in less
    if np.any(self_angle < wrap_angle_floor) or np.any(self_angle >= wrap_angle):
  /Users/eisenham/anaconda3/envs/spec3/lib/python3.5/site-packages/astropy/coordinates/angles.py:625: RuntimeWarning: invalid value encountered in greater_equal
    if np.any(self_angle < wrap_angle_floor) or np.any(self_angle >= wrap_angle):
  /Users/eisenham/anaconda3/envs/spec3/lib/python3.5/site-packages/astropy/coordinates/angles.py:513: RuntimeWarning: invalid value encountered in less
    if np.any(angles.value < lower) or np.any(angles.value > upper):
  /Users/eisenham/anaconda3/envs/spec3/lib/python3.5/site-packages/astropy/coordinates/angles.py:513: RuntimeWarning: invalid value encountered in greater
    if np.any(angles.value < lower) or np.any(angles.value > upper):

-- Docs: http://doc.pytest.org/en/latest/warnings.html
===================================================================== 1 failed, 4 warnings in 3.08 seconds =====================================================================
```

### PR DESCRIPTION
**Pull request by jdavies-st**
Implements new method for computing the output frame wcs for NIRSpec from the intermediate `slit_frame` in the WCS transform.

Resolves #1006

### CODE REVIEW

**Comment by hbushouse** [comment]
Fixes #613

**Comment by hbushouse** [comment]
Merging now to get it into overnight build and tomorrow's regression test run.

**Comment by stsci-hack** [comment]
This PR unfortunately introduced changes to resample that were incompatible with PR #1369.  That incompatibility resulted in the outlier_detection failing in the regression tests.  Specifically, the build_driz_weight code is a method here whereas it is being called as a function in the new outlier_detection code.  How would it be best to sort this out?

**Comment by jdavies-st** [comment]
Thanks Warren.  Looking into this.

**Pull request merged**
